version: "3.9"

services:
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: rabbitmq-container
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "C:\\Users\\Família\\Documents\\Modelos Personalizados do Office\\Nuvem\\RabbitMQ:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin